import { useEffect, useState } from "react";
import { Clock, IndianRupee, Search, ShoppingBag } from "lucide-react";
import { useCart } from "../context/CartContext";
import { getImageUrl, getRecipes } from "../services/api";

const CategoryMenu = ({ category, title, description }) => {
  const [recipes, setRecipes] = useState([]);
  const [search, setSearch] = useState("");
  const { cartItems, addToCart, removeFromCart } = useCart();
  useEffect(() => { getRecipes().then((items) => setRecipes(items.filter((recipe) => recipe.category === category && recipe.isAvailable !== false))).catch(() => setRecipes([])); }, [category]);
  const visible = recipes.filter((recipe) => recipe.name.toLowerCase().includes(search.toLowerCase()));
  const quantity = (id) => cartItems.find((item) => item.id === id)?.quantity || 0;
  return <div className="min-h-screen bg-slate-50 px-4 py-10 dark:bg-slate-900"><div className="mx-auto max-w-7xl"><div className="mb-8 text-center"><ShoppingBag className="mx-auto mb-3 text-orange-500" size={38} /><h1 className="text-3xl font-bold text-slate-900 dark:text-white">{title} Menu</h1><p className="mt-2 text-slate-500 dark:text-slate-400">{description}</p></div><div className="relative mx-auto mb-8 max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${title.toLowerCase()}`} className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white" /></div>{visible.length === 0 ? <div className="py-20 text-center text-slate-500">No {title.toLowerCase()} dishes available.</div> : <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((recipe) => <article key={recipe._id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><img src={getImageUrl(recipe.image)} alt={recipe.name} className="h-48 w-full object-cover" /><div className="p-5"><h2 className="font-bold text-slate-900 dark:text-white">{recipe.name}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-500 dark:text-slate-400">{recipe.description}</p><div className="mt-4 flex justify-between text-sm"><span className="flex items-center font-bold text-orange-500"><IndianRupee size={14} />{recipe.price}</span><span className="flex items-center gap-1 text-slate-500"><Clock size={14} />{recipe.preparationTime}</span></div>{quantity(recipe._id) ? <div className="mt-4 flex items-center justify-between rounded-xl bg-orange-50 p-2"><button onClick={() => removeFromCart(recipe._id)} className="h-8 w-8 rounded-full bg-white text-orange-500">-</button><span className="font-bold text-orange-600">{quantity(recipe._id)}</span><button onClick={() => addToCart({ id: recipe._id, name: recipe.name, price: recipe.price, image: recipe.image })} className="h-8 w-8 rounded-full bg-orange-500 text-white">+</button></div> : <button onClick={() => addToCart({ id: recipe._id, name: recipe.name, price: recipe.price, image: recipe.image })} className="mt-4 w-full rounded-xl bg-orange-500 py-2.5 text-sm font-semibold text-white">Add to cart</button>}</div></article>)}</div>}</div></div>;
};

export default CategoryMenu;
